language: python

matrix:
  fast_finish: true
  include:
    - python: "2.7"
      env: TOXENV=py27 PYPI=true
      os: linux
      before_install:
        - sudo apt update
        - sudo apt install python-dev libgirepository1.0-dev libcairo2-dev gir1.2-secret-1
        - pip install --upgrade pip
    - python: "3.5"
      env: TOXENV=py35
      os: linux
      before_install:
        - sudo apt update
        - sudo apt install python3-dev libgirepository1.0-dev libcairo2-dev gir1.2-secret-1
        - pip install --upgrade pip

    ## Somehow cryptography is not able to be compiled and installed on Python 3.6
    #- python: "3.6"
    #  env:
    #    - TOXENV=py36
    #    - CRYPTOGRAPHY_DONT_BUILD_RUST=1
    #  os: linux
    #  before_install:
    #    - sudo apt update
    #    - sudo apt install python3-dev libgirepository1.0-dev libcairo2-dev gir1.2-secret-1
    #    - pip install --upgrade pip

    - python: "3.7"
      env: TOXENV=py37
      os: linux
      dist: xenial
      before_install:
        - sudo apt update
        - sudo apt install python3-dev libgirepository1.0-dev libcairo2-dev gir1.2-secret-1
        - pip install --upgrade pip
    - python: "3.8"
      env: TOXENV=py38
      os: linux
      dist: xenial
      before_install:
        - sudo apt update
        - sudo apt install python3-dev libgirepository1.0-dev libcairo2-dev gir1.2-secret-1
        - pip install --upgrade pip
    - name: "Python 3.7 on macOS"
      env: TOXENV=py37
      os: osx
      osx_image: xcode10.2
      language: shell
    - name: "Python 2.7 on Windows"
      env: TOXENV=py27 PATH=/c/Python27:/c/Python27/Scripts:$PATH
      os: windows
      before_install:
        - choco install python2
        - pip install --upgrade --user pip
      language: shell
    - name: "Python 3.5 on Windows"
      env: TOXENV=py35 PATH=/c/Python35:/c/Python35/Scripts:$PATH
      os: windows
      before_install:
        - choco install python3 --version 3.5.4
        - pip install --upgrade --user pip
      language: shell
    - name: "Python 3.7 on Windows"
      env: TOXENV=py37 PATH=/c/Python37:/c/Python37/Scripts:$PATH
      os: windows
      before_install:
        - choco install python3 --version 3.7.3
        - pip install --upgrade --user pip
      language: shell

install:
  - pip install tox pylint
  - pip install .

script:
  - # Difficult to get .pylintrc working on both Python 2 & 3, and we don't have to
  - if [ "$TOXENV" = "py37"]; then pylint msal_extensions; fi
  - tox

deploy:
  - # test pypi
    provider: pypi
    distributions: "sdist bdist_wheel"
    server: https://test.pypi.org/legacy/
    user: "nugetaad"
    password:
      secure: dpNi6BsZyiAx/gkxJ5Mz6m2yDz2dRGWsSgS5pF+ywNzgHJ6+0e234GyLbSUY5bFeeA7WtOr4is3bxSLB/6tTWDVWdw3TL4FGlDM/54MSLWg8R5bR9PRwO+VU1kvQ03yz+B9mTpzuiwL2e+OSwcwo97jForADzmSRA5OpEq5Z7zAs7WR8J2tyhl+288NwLtKJMVy39UmPl9oifu6/5RfBn7EWLmC7MrMFhHTb2Gj7fJWw4u+5vx9bsQ7ubfiwPbRAtYXLz6wDMtwtFzwme4zZPg5HwWCn0WWlX4b6x7xXirZ7yKsy9iACLgTrLMeAkferrex7f03NFeIDobasML+fLbZufATaL3M97kNGZwulEYNp2+RWyLu/NW6FoZCbS+cSL8HuFnkIDHzEoO56ItMiD9EH47q/NeKgwrrzKjfY+KzaMQOYLlVgCa4WrIeFh5CkwJ4RHrfanMIV2vbEvMxsnHc/mZ+yvgBOFoBNXYN1HEDzEv1NxDPcyt7MBlPUVinEreQaHba7w6qH9Rf0eWgfW2ypBXe+nHaZxQgaGC6J+WGUkzalYQspmHVU4CcuwJa55kuchJs/gbyZKkyK6P8uD5IP6VZiavwZcjWcfvwbZaLeOqzSDVCDMg8M2zYZHoa+6ZR4EgDVW7RvaRvjvvhPTPj5twmLf3YYVJtHIyJSLug=
    on:
      branch: master
      tags: false
      condition: $PYPI = "true"

  - # production pypi
    provider: pypi
    distributions: "sdist bdist_wheel"
    user: "nugetaad"
    password:
      secure: dpNi6BsZyiAx/gkxJ5Mz6m2yDz2dRGWsSgS5pF+ywNzgHJ6+0e234GyLbSUY5bFeeA7WtOr4is3bxSLB/6tTWDVWdw3TL4FGlDM/54MSLWg8R5bR9PRwO+VU1kvQ03yz+B9mTpzuiwL2e+OSwcwo97jForADzmSRA5OpEq5Z7zAs7WR8J2tyhl+288NwLtKJMVy39UmPl9oifu6/5RfBn7EWLmC7MrMFhHTb2Gj7fJWw4u+5vx9bsQ7ubfiwPbRAtYXLz6wDMtwtFzwme4zZPg5HwWCn0WWlX4b6x7xXirZ7yKsy9iACLgTrLMeAkferrex7f03NFeIDobasML+fLbZufATaL3M97kNGZwulEYNp2+RWyLu/NW6FoZCbS+cSL8HuFnkIDHzEoO56ItMiD9EH47q/NeKgwrrzKjfY+KzaMQOYLlVgCa4WrIeFh5CkwJ4RHrfanMIV2vbEvMxsnHc/mZ+yvgBOFoBNXYN1HEDzEv1NxDPcyt7MBlPUVinEreQaHba7w6qH9Rf0eWgfW2ypBXe+nHaZxQgaGC6J+WGUkzalYQspmHVU4CcuwJa55kuchJs/gbyZKkyK6P8uD5IP6VZiavwZcjWcfvwbZaLeOqzSDVCDMg8M2zYZHoa+6ZR4EgDVW7RvaRvjvvhPTPj5twmLf3YYVJtHIyJSLug=
    on:
      branch: master
      tags: true
      condition: $PYPI = "true"
