# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
  pull_request:
    branches: [ dev ]
    # This guards against unknown PR until a community member vet it and label it.
    types: [ labeled ]

jobs:
  ci:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, 2.7]
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#using-environment-variables-in-a-matrix
          - python-version: 3.7
            toxenv: "py37"
          - python-version: 3.8
            toxenv: "py38"
          - python-version: 3.9
            toxenv: "py39"
          - python-version: 2.7
            toxenv: "py27"
          - python-version: 3.9
            os: ubuntu-latest
            lint: "true"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Linux dependencies for Python 2
      if: ${{ matrix.os == 'ubuntu-latest' && matrix.python-version == '2.7' }}
      run: |
        sudo apt update
        sudo apt install python-dev libgirepository1.0-dev libcairo2-dev gir1.2-secret-1
    - name: Install Linux dependencies for Python 3
      if: ${{ matrix.os == 'ubuntu-latest' && matrix.python-version != '2.7' }}
      run: |
        sudo apt update
        sudo apt install python3-dev libgirepository1.0-dev libcairo2-dev gir1.2-secret-1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pylint tox
        pip install .
    - name: Lint
      if: ${{ matrix.lint == 'true' }}
      run: |
        pylint msal_extensions
        # stop the build if there are Python syntax errors or undefined names
        #flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        #flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test
      env:
        TOXENV: ${{ matrix.toxenv }}
      run: |
        tox
